

export const states = [
    { value: 'AN', label: 'Andaman and Nicobar Islands' },
    { value: 'AP', label: 'Andhra Pradesh' },
    { value: 'AR', label: 'Arunachal Pradesh' },
    { value: 'AS', label: 'Assam' },
    { value: 'BR', label: 'Bihar' },
    { value: 'CH', label: 'Chandigarh' },
    { value: 'CT', label: 'Chhattisgarh' },
    { value: 'DN', label: 'Dadra and Nagar Haveli and Daman and Diu' },
    { value: 'DL', label: 'Delhi' },
    { value: 'GA', label: 'Goa' },
    { value: 'GJ', label: 'Gujarat' },
    { value: 'HR', label: 'Haryana' },
    { value: 'HP', label: 'Himachal Pradesh' },
    { value: 'JK', label: 'Jammu and Kashmir' },
    { value: 'JH', label: 'Jharkhand' },
    { value: 'KA', label: 'Karnataka' },
    { value: 'KL', label: 'Kerala' },
    { value: 'LA', label: 'Ladakh' },
    { value: 'LD', label: 'Lakshadweep' },
    { value: 'MP', label: 'Madhya Pradesh' },
    { value: 'MH', label: 'Maharashtra' },
    { value: 'MN', label: 'Manipur' },
    { value: 'ML', label: 'Meghalaya' },
    { value: 'MZ', label: 'Mizoram' },
    { value: 'NL', label: 'Nagaland' },
    { value: 'OR', label: 'Odisha' },
    { value: 'PY', label: 'Puducherry' },
    { value: 'PB', label: 'Punjab' },
    { value: 'RJ', label: 'Rajasthan' },
    { value: 'SK', label: 'Sikkim' },
    { value: 'TN', label: 'Tamil Nadu' },
    { value: 'TG', label: 'Telangana' },
    { value: 'TR', label: 'Tripura' },
    { value: 'UP', label: 'Uttar Pradesh' },
    { value: 'UT', label: 'Uttarakhand' },
    { value: 'WB', label: 'West Bengal' },
];

export const districts = [
    // Maharashtra
    { value: 'ahmednagar', label: 'Ahmednagar', state: 'MH' },
    { value: 'akola', label: 'Akola', state: 'MH' },
    { value: 'amravati', label: 'Amravati', state: 'MH' },
    { value: 'aurangabad', label: 'Aurangabad', state: 'MH' },
    { value: 'beed', label: 'Beed', state: 'MH' },
    { value: 'bhandara', label: 'Bhandara', state: 'MH' },
    { value: 'buldhana', label: 'Buldhana', state: 'MH' },
    { value: 'chandrapur', label: 'Chandrapur', state: 'MH' },
    { value: 'dhule', label: 'Dhule', state: 'MH' },
    { value: 'gadchiroli', label: 'Gadchiroli', state: 'MH' },
    { value: 'gondia', label: 'Gondia', state: 'MH' },
    { value: 'hingoli', label: 'Hingoli', state: 'MH' },
    { value: 'jalgaon', label: 'Jalgaon', state: 'MH' },
    { value: 'jalna', label: 'Jalna', state: 'MH' },
    { value: 'kolhapur', label: 'Kolhapur', state: 'MH' },
    { value: 'latur', label: 'Latur', state: 'MH' },
    { value: 'mumbai-city', label: 'Mumbai City', state: 'MH' },
    { value: 'mumbai-suburban', label: 'Mumbai Suburban', state: 'MH' },
    { value: 'nagpur', label: 'Nagpur', state: 'MH' },
    { value: 'nanded', label: 'Nanded', state: 'MH' },
    { value: 'nandurbar', label: 'Nandurbar', state: 'MH' },
    { value: 'nashik', label: 'Nashik', state: 'MH' },
    { value: 'osmanabad', label: 'Osmanabad', state: 'MH' },
    { value: 'palghar', label: 'Palghar', state: 'MH' },
    { value: 'parbhani', label: 'Parbhani', state: 'MH' },
    { value: 'pune', label: 'Pune', state: 'MH' },
    { value: 'raigad', label: 'Raigad', state: 'MH' },
    { value: 'ratnagiri', label: 'Ratnagiri', state: 'MH' },
    { value: 'sangli', label: 'Sangli', state: 'MH' },
    { value: 'satara', label: 'Satara', state: 'MH' },
    { value: 'sindhudurg', label: 'Sindhudurg', state: 'MH' },
    { value: 'solapur', label: 'Solapur', state: 'MH' },
    { value: 'thane', label: 'Thane', state: 'MH' },
    { value: 'wardha', label: 'Wardha', state: 'MH' },
    { value: 'washim', label: 'Washim', state: 'MH' },
    { value: 'yavatmal', label: 'Yavatmal', state: 'MH' },

    // Gujarat
    { value: 'ahmedabad', label: 'Ahmedabad', state: 'GJ' },
    { value: 'amreli', label: 'Amreli', state: 'GJ' },
    { value: 'anand', label: 'Anand', state: 'GJ' },
    { value: 'aravalli', label: 'Aravalli', state: 'GJ' },
    { value: 'banaskantha', label: 'Banaskantha', state: 'GJ' },
    { value: 'bharuch', label: 'Bharuch', state: 'GJ' },
    { value: 'bhavnagar', label: 'Bhavnagar', state: 'GJ' },
    { value: 'botad', label: 'Botad', state: 'GJ' },
    { value: 'chhota-udaipur', label: 'Chhota Udaipur', state: 'GJ' },
    { value: 'dahod', label: 'Dahod', state: 'GJ' },
    { value: 'dang', label: 'Dang', state: 'GJ' },
    { value: 'devbhoomi-dwarka', label: 'Devbhoomi Dwarka', state: 'GJ' },
    { value: 'gandhinagar', label: 'Gandhinagar', state: 'GJ' },
    { value: 'gir-somnath', label: 'Gir Somnath', state: 'GJ' },
    { value: 'jamnagar', label: 'Jamnagar', state: 'GJ' },
    { value: 'junagadh', label: 'Junagadh', state: 'GJ' },
    { value: 'kheda', label: 'Kheda', state: 'GJ' },
    { value: 'kutch', label: 'Kutch', state: 'GJ' },
    { value: 'mahisagar', label: 'Mahisagar', state: 'GJ' },
    { value: 'mehsana', label: 'Mehsana', state: 'GJ' },
    { value: 'morbi', label: 'Morbi', state: 'GJ' },
    { value: 'narmada', label: 'Narmada', state: 'GJ' },
    { value: 'navsari', label: 'Navsari' },
    { value: 'panchmahal', label: 'Panchmahal', state: 'GJ' },
    { value: 'patan', label: 'Patan', state: 'GJ' },
    { value: 'porbandar', label: 'Porbandar', state: 'GJ' },
    { value: 'rajkot', label: 'Rajkot', state: 'GJ' },
    { value: 'sabarkantha', label: 'Sabarkantha', state: 'GJ' },
    { value: 'surat', label: 'Surat', state: 'GJ' },
    { value: 'surendranagar', label: 'Surendranagar', state: 'GJ' },
    { value: 'tapi', label: 'Tapi', state: 'GJ' },
    { value: 'vadodara', label: 'Vadodara', state: 'GJ' },
    { value: 'valsad', label: 'Valsad', state: 'GJ' },
];

export const talukas = [
    // Maharashtra -> Ahmednagar
    { value: 'nagar', label: 'Nagar', district: 'ahmednagar' },
    { value: 'pathardi', label: 'Pathardi', district: 'ahmednagar' },
    { value: 'karjat', label: 'Karjat', district: 'ahmednagar' },
    { value: 'jamkhed', label: 'Jamkhed', district: 'ahmednagar' },
    { value: 'shevgaon', label: 'Shevgaon', district: 'ahmednagar' },
    { value: 'shrigonda', label: 'Shrigonda', district: 'ahmednagar' },
    { value: 'parner', label: 'Parner', district: 'ahmednagar' },
    { value: 'sangamner', label: 'Sangamner', district: 'ahmednagar' },
    { value: 'kopargaon', label: 'Kopargaon', district: 'ahmednagar' },
    { value: 'akole', label: 'Akole', district: 'ahmednagar' },
    { value: 'shrirampur', label: 'Shrirampur', district: 'ahmednagar' },
    { value: 'nevasa', label: 'Nevasa', district: 'ahmednagar' },
    { value: 'rahata', label: 'Rahata', district: 'ahmednagar' },
    { value: 'rahuri', label: 'Rahuri', district: 'ahmednagar' },
    // Maharashtra -> Akola
    { value: 'akot', label: 'Akot', district: 'akola' },
    { value: 'telhara', label: 'Telhara', district: 'akola' },
    { value: 'akola', label: 'Akola', district: 'akola' },
    { value: 'balapur', label: 'Balapur', district: 'akola' },
    { value: 'patoor', label: 'Patoor', district: 'akola' },
    { value: 'murtijapur', label: 'Murtijapur', district: 'akola' },
    { value: 'barshitakli', label: 'Barshitakli', district: 'akola' },
    // Maharashtra -> Amravati
    { value: 'amravati', label: 'Amravati', district: 'amravati' },
    { value: 'bhatkuli', label: 'Bhatkuli', district: 'amravati' },
    { value: 'nandgaon-khandeshwar', label: 'Nandgaon Khandeshwar', district: 'amravati' },
    { value: 'chandur-railway', label: 'Chandur Railway', district: 'amravati' },
    { value: 'tiosa', label: 'Tiosa', district: 'amravati' },
    { value: 'dhamangaon-railway', label: 'Dhamangaon Railway', district: 'amravati' },
    { value: 'morshi', label: 'Morshi', district: 'amravati' },
    { value: 'warud', label: 'Warud', district: 'amravati' },
    { value: 'achlapur', label: 'Achalpur', district: 'amravati' },
    { value: 'chandur-bazar', label: 'Chandur Bazar', district: 'amravati' },
    { value: 'daryapur', label: 'Daryapur', district: 'amravati' },
    { value: 'anjangaon-surji', label: 'Anjangaon Surji', district: 'amravati' },
    { value: 'dharni', label: 'Dharni', district: 'amravati' },
    { value: 'chikhaldara', label: 'Chikhaldara', district: 'amravati' },
    // Maharashtra -> Aurangabad
    { value: 'aurangabad', label: 'Aurangabad', district: 'aurangabad' },
    { value: 'kannad', label: 'Kannad', district: 'aurangabad' },
    { value: 'soegaon', label: 'Soegaon', district: 'aurangabad' },
    { value: 'sillod', label: 'Sillod', district: 'aurangabad' },
    { value: 'phulambri', label: 'Phulambri', district: 'aurangabad' },
    { value: 'khuldabad', label: 'Khuldabad', district: 'aurangabad' },
    { value: 'vaijapur', label: 'Vaijapur', district: 'aurangabad' },
    { value: 'gangapur', label: 'Gangapur', district: 'aurangabad' },
    { value: 'paithan', label: 'Paithan', district: 'aurangabad' },
    // Maharashtra -> Beed
    { value: 'beed', label: 'Beed', district: 'beed' },
    { value: 'wadwani', label: 'Wadwani', district: 'beed' },
    { value: 'kaij', label: 'Kaij', district: 'beed' },
    { value: 'ashti-beed', label: 'Ashti', district: 'beed' },
    { value: 'patoda', label: 'Patoda', district: 'beed' },
    { value: 'shirur-kasar', label: 'Shirur Kasar', district: 'beed' },
    { value: 'georai', label: 'Georai', district: 'beed' },
    { value: 'manjlegaon', label: 'Manjlegaon', district: 'beed' },
    { value: 'ambajogai', label: 'Ambajogai', district: 'beed' },
    { value: 'parli', label: 'Parli', district: 'beed' },
    { value: 'dharur', label: 'Dharur', district: 'beed' },
    // Maharashtra -> Bhandara
    { value: 'bhandara', label: 'Bhandara', district: 'bhandara' },
    { value: 'tumsar', label: 'Tumsar', district: 'bhandara' },
    { value: 'pauni', label: 'Pauni', district: 'bhandara' },
    { value: 'mohadi', label: 'Mohadi', district: 'bhandara' },
    { value: 'sakoli', label: 'Sakoli', district: 'bhandara' },
    { value: 'lakhni', label: 'Lakhni', district: 'bhandara' },
    { value: 'lakhandur', label: 'Lakhandur', district: 'bhandara' },
    // Maharashtra -> Buldhana
    { value: 'buldhana', label: 'Buldhana', district: 'buldhana' },
    { value: 'chikhli', label: 'Chikhli', district: 'buldhana' },
    { value: 'deulgaon-raja', label: 'Deulgaon Raja', district: 'buldhana' },
    { value: 'jalgaon-jamod', label: 'Jalgaon Jamod', district: 'buldhana' },
    { value: 'sangrampur', label: 'Sangrampur', district: 'buldhana' },
    { value: 'malkapur', label: 'Malkapur', district: 'buldhana' },
    { value: 'motala', label: 'Motala', district: 'buldhana' },
    { value: 'nandura', label: 'Nandura', district: 'buldhana' },
    { value: 'khamgaon', label: 'Khamgaon', district: 'buldhana' },
    { value: 'shegaon', label: 'Shegaon', district: 'buldhana' },
    { value: 'mehkar', label: 'Mehkar', district: 'buldhana' },
    { value: 'sindkhed-raja', label: 'Sindkhed Raja', district: 'buldhana' },
    { value: 'lonar', label: 'Lonar', district: 'buldhana' },
    // Maharashtra -> Chandrapur
    { value: 'chandrapur', label: 'Chandrapur', district: 'chandrapur' },
    { value: 'saoli', label: 'Saoli', district: 'chandrapur' },
    { value: 'mul', label: 'Mul', district: 'chandrapur' },
    { value: 'ballarpur', label: 'Ballarpur', district: 'chandrapur' },
    { value: 'pombhurna', label: 'Pombhurna', district: 'chandrapur' },
    { value: 'gondpimpri', label: 'Gondpimpri', district: 'chandrapur' },
    { value: 'warora', label: 'Warora', district: 'chandrapur' },
    { value: 'bhadravati', label: 'Bhadravati', district: 'chandrapur' },
    { value: 'chimur', label: 'Chimur', district: 'chandrapur' },
    { value: 'bramhapuri', label: 'Bramhapuri', district: 'chandrapur' },
    { value: 'nagbhid', label: 'Nagbhid', district: 'chandrapur' },
    { value: 'sindewahi', label: 'Sindewahi', district: 'chandrapur' },
    { value: 'rajura', label: 'Rajura', district: 'chandrapur' },
    { value: 'korphana', label: 'Korphana', district: 'chandrapur' },
    { value: 'jiwati', label: 'Jiwati', district: 'chandrapur' },
    // Maharashtra -> Dhule
    { value: 'dhule', label: 'Dhule', district: 'dhule' },
    { value: 'sakri', label: 'Sakri', district: 'dhule' },
    { value: 'shindkheda', label: 'Shindkheda', district: 'dhule' },
    { value: 'shirpur', label: 'Shirpur', district: 'dhule' },
    // Maharashtra -> Gadchiroli
    { value: 'gadchiroli', label: 'Gadchiroli', district: 'gadchiroli' },
    { value: 'dhanora', label: 'Dhanora', district: 'gadchiroli' },
    { value: 'chamorshi', label: 'Chamorshi', district: 'gadchiroli' },
    { value: 'mulchera', label: 'Mulchera', district: 'gadchiroli' },
    { value: 'desaignaj', label: 'Desaignaj (Vadasa)', district: 'gadchiroli' },
    { value: 'armori', label: 'Armori', district: 'gadchiroli' },
    { value: 'kurkheda', label: 'Kurkheda', district: 'gadchiroli' },
    { value: 'korchi', label: 'Korchi', district: 'gadchiroli' },
    { value: 'ahiri', label: 'Ahiri', district: 'gadchiroli' },
    { value: 'bhamragad', label: 'Bhamragad', district: 'gadchiroli' },
    { value: 'ettapalli', label: 'Ettapalli', district: 'gadchiroli' },
    { value: 'sironcha', label: 'Sironcha', district: 'gadchiroli' },
    // Maharashtra -> Gondia
    { value: 'gondia', label: 'Gondia', district: 'gondia' },
    { value: 'goregaon', label: 'Goregaon', district: 'gondia' },
    { value: 'tiroda', label: 'Tiroda', district: 'gondia' },
    { value: 'arjuna-morgaon', label: 'Arjuni Morgaon', district: 'gondia' },
    { value: 'deori', label: 'Deori', district: 'gondia' },
    { value: 'amgaon', label: 'Amgaon', district: 'gondia' },
    { value: 'salekasa', label: 'Salekasa', district: 'gondia' },
    { value: 'sadak-arjuna', label: 'Sadak Arjuni', district: 'gondia' },
    // Maharashtra -> Hingoli
    { value: 'hingoli', label: 'Hingoli', district: 'hingoli' },
    { value: 'kalamnuri', label: 'Kalamnuri', district: 'hingoli' },
    { value: 'sengaon', label: 'Sengaon', district: 'hingoli' },
    { value: 'aumdha-nagnath', label: 'Aundha Nagnath', district: 'hingoli' },
    { value: 'basmath', label: 'Basmath', district: 'hingoli' },
    // Maharashtra -> Jalgaon
    { value: 'jalgaon', label: 'Jalgaon', district: 'jalgaon' },
    { value: 'jamner', label: 'Jamner', district: 'jalgaon' },
    { value: 'erandol', label: 'Erandol', district: 'jalgaon' },
    { value: 'dharangaon', label: 'Dharangaon', district: 'jalgaon' },
    { value: 'bhusawal', label: 'Bhusawal', district: 'jalgaon' },
    { value: 'raver', label: 'Raver', district: 'jalgaon' },
    { value: 'yawal', label: 'Yawal', district: 'jalgaon' },
    { value: 'chopda', label: 'Chopda', district: 'jalgaon' },
    { value: 'amalner', label: 'Amalner', district: 'jalgaon' },
    { value: 'parola', label: 'Parola', district: 'jalgaon' },
    { value: 'chalisgaon', label: 'Chalisgaon', district: 'jalgaon' },
    { value: 'bhadgaon', label: 'Bhadgaon', district: 'jalgaon' },
    { value: 'pachora', label: 'Pachora', district: 'jalgaon' },
    { value: 'muktainagar', label: 'Muktainagar', district: 'jalgaon' },
    { value: 'bodwad', label: 'Bodwad', district: 'jalgaon' },
    // Maharashtra -> Jalna
    { value: 'jalna', label: 'Jalna', district: 'jalna' },
    { value: 'badnapur', label: 'Badnapur', district: 'jalna' },
    { value: 'bhokardan', label: 'Bhokardan', district: 'jalna' },
    { value: 'jafrabad', label: 'Jafrabad', district: 'jalna' },
    { value: 'partur', label: 'Partur', district: 'jalna' },
    { value: 'mantha', label: 'Mantha', district: 'jalna' },
    { value: 'ghansawangi', label: 'Ghansawangi', district: 'jalna' },
    { value: 'ambad', label: 'Ambad', district: 'jalna' },
    // Maharashtra -> Kolhapur
    { value: 'karvir', label: 'Karvir', district: 'kolhapur' },
    { value: 'panhala', label: 'Panhala', district: 'kolhapur' },
    { value: 'hatkanangle', label: 'Hatkanangle', district: 'kolhapur' },
    { value: 'shirol', label: 'Shirol', district: 'kolhapur' },
    { value: 'kagal', label: 'Kagal', district: 'kolhapur' },
    { value: 'gadhinglaj', label: 'Gadhinglaj', district: 'kolhapur' },
    { value: 'chandgad', label: 'Chandgad', district: 'kolhapur' },
    { value: 'ajra', label: 'Ajra', district: 'kolhapur' },
    { value: 'bhudargad', label: 'Bhudargad', district: 'kolhapur' },
    { value: 'radhanagari', label: 'Radhanagari', district: 'kolhapur' },
    { value: 'gaganbawada', label: 'Gaganbawada', district: 'kolhapur' },
    { value: 'shahuwadi', label: 'Shahuwadi', district: 'kolhapur' },
    // Maharashtra -> Latur
    { value: 'latur', label: 'Latur', district: 'latur' },
    { value: 'renapur', label: 'Renapur', district: 'latur' },
    { value: 'ahmedpur', label: 'Ahmedpur', district: 'latur' },
    { value: 'jalkot', label: 'Jalkot', district: 'latur' },
    { value: 'chakur', label: 'Chakur', district: 'latur' },
    { value: 'shirur-ananantpal', label: 'Shirur Anantpal', district: 'latur' },
    { value: 'ausa', label: 'Ausa', district: 'latur' },
    { value: 'nilanga', label: 'Nilanga', district: 'latur' },
    { value: 'deoni', label: 'Deoni', district: 'latur' },
    { value: 'udgir', label: 'Udgir', district: 'latur' },
    // Maharashtra -> Mumbai City
    // No Talukas for Mumbai City
    // Maharashtra -> Mumbai Suburban
    { value: 'kurla', label: 'Kurla', district: 'mumbai-suburban' },
    { value: 'andheri', label: 'Andheri', district: 'mumbai-suburban' },
    { value: 'borivali', label: 'Borivali', district: 'mumbai-suburban' },
    // Maharashtra -> Nagpur
    { value: 'nagpur-urban', label: 'Nagpur (Urban)', district: 'nagpur' },
    { value: 'nagpur-rural', label: 'Nagpur (Rural)', district: 'nagpur' },
    { value: 'kamptee', label: 'Kamptee', district: 'nagpur' },
    { value: 'hingna', label: 'Hingna', district: 'nagpur' },
    { value: 'katol', label: 'Katol', district: 'nagpur' },
    { value: 'narkhed', label: 'Narkhed', district: 'nagpur' },
    { value: 'savner', label: 'Savner', district: 'nagpur' },
    { value: 'parseoni', label: 'Parseoni', district: 'nagpur' },
    { value: 'ramtek', label: 'Ramtek', district: 'nagpur' },
    { value: 'mouda', label: 'Mouda', district: 'nagpur' },
    { value: 'umred', label: 'Umred', district: 'nagpur' },
    { value: 'kuhi', label: 'Kuhi', district: 'nagpur' },
    { value: 'bhiwapur', label: 'Bhiwapur', district: 'nagpur' },
    // Maharashtra -> Nanded
    { value: 'nanded', label: 'Nanded', district: 'nanded' },
    { value: 'mudkhed', label: 'Mudkhed', district: 'nanded' },
    { value: 'aradhapur', label: 'Ardhapur', district: 'nanded' },
    { value: 'bhokar', label: 'Bhokar', district: 'nanded' },
    { value: 'umri', label: 'Umri', district: 'nanded' },
    { value: 'kandhar', label: 'Kandhar', district: 'nanded' },
    { value: 'loha', label: 'Loha', district: 'nanded' },
    { value: 'kinwat', label: 'Kinwat', district: 'nanded' },
    { value: 'mahore', label: 'Mahore', district: 'nanded' },
    { value: 'hadgaon', label: 'Hadgaon', district: 'nanded' },
    { value: 'himayatnagar', label: 'Himayatnagar', district: 'nanded' },
    { value: 'deglur', label: 'Deglur', district: 'nanded' },
    { value: 'biloli', label: 'Biloli', district: 'nanded' },
    { value: 'dharmabad', label: 'Dharmabad', district: 'nanded' },
    { value: 'naigaon', label: 'Naigaon', district: 'nanded' },
    { value: 'mukhed', label: 'Mukhed', district: 'nanded' },
    // Maharashtra -> Nandurbar
    { value: 'nandurbar', label: 'Nandurbar', district: 'nandurbar' },
    { value: 'navapur', label: 'Navapur', district: 'nandurbar' },
    { value: 'shahada', label: 'Shahada', district: 'nandurbar' },
    { value: 'taloda', label: 'Taloda', district: 'nandurbar' },
    { value: 'akkalkuwa', label: 'Akkalkuwa', district: 'nandurbar' },
    { value: 'akrani', label: 'Akrani', district: 'nandurbar' },
    // Maharashtra -> Nashik
    { value: 'nashik', label: 'Nashik', district: 'nashik' },
    { value: 'igatpuri', label: 'Igatpuri', district: 'nashik' },
    { value: 'dindori', label: 'Dindori', district: 'nashik' },
    { value: 'peint', label: 'Peint', district: 'nashik' },
    { value: 'trimbakeshwar', label: 'Trimbakeshwar', district: 'nashik' },
    { value: 'kalwan', label: 'Kalwan', district: 'nashik' },
    { value: 'deola', label: 'Deola', district: 'nashik' },
    { value: 'surgana', label: 'Surgana', district: 'nashik' },
    { value: 'baglan', label: 'Baglan', district: 'nashik' },
    { value: 'malegaon', label: 'Malegaon', district: 'nashik' },
    { value: 'chandwad', label: 'Chandwad', district: 'nashik' },
    { value: 'nandgaon', label: 'Nandgaon', district: 'nashik' },
    { value: 'yeola', label: 'Yeola', district: 'nashik' },
    { value: 'niphad', label: 'Niphad', district: 'nashik' },
    { value: 'sinnar', label: 'Sinnar', district: 'nashik' },
    // Maharashtra -> Osmanabad
    { value: 'osmanabad', label: 'Osmanabad', district: 'osmanabad' },
    { value: 'tuljapur', label: 'Tuljapur', district: 'osmanabad' },
    { value: 'bhum', label: 'Bhum', district: 'osmanabad' },
    { value: 'paranda', label: 'Paranda', district: 'osmanabad' },
    { value: 'washi', label: 'Washi', district: 'osmanabad' },
    { value: 'kalamb-osmanabad', label: 'Kalamb', district: 'osmanabad' },
    { value: 'umaraga', label: 'Umaraga', district: 'osmanabad' },
    { value: 'lohara', label: 'Lohara', district: 'osmanabad' },
    // Maharashtra -> Palghar
    { value: 'palghar', label: 'Palghar', district: 'palghar' },
    { value: 'vasai', label: 'Vasai', district: 'palghar' },
    { value: 'dahanu', label: 'Dahanu', district: 'palghar' },
    { value: 'talasari', label: 'Talasari', district: 'palghar' },
    { value: 'jawhar', label: 'Jawhar', district: 'palghar' },
    { value: 'mokhada', label: 'Mokhada', district: 'palghar' },
    { value: 'wada', label: 'Wada', district: 'palghar' },
    { value: 'vikramgad', label: 'Vikramgad', district: 'palghar' },
    // Maharashtra -> Parbhani
    { value: 'parbhani', label: 'Parbhani', district: 'parbhani' },
    { value: 'sonpeth', label: 'Sonpeth', district: 'parbhani' },
    { value: 'gangakhed', label: 'Gangakhed', district: 'parbhani' },
    { value: 'palam', label: 'Palam', district: 'parbhani' },
    { value: 'purna', label: 'Purna', district: 'parbhani' },
    { value: 'sailu', label: 'Sailu', district: 'parbhani' },
    { value: 'jintur', label: 'Jintur', district: 'parbhani' },
    { value: 'manwath', label: 'Manwath', district: 'parbhani' },
    { value: 'pathri', label: 'Pathri', district: 'parbhani' },
    // Maharashtra -> Pune
    { value: 'pune-city', label: 'Pune City', district: 'pune' },
    { value: 'haveli', label: 'Haveli', district: 'pune' },
    { value: 'khed', label: 'Khed', district: 'pune' },
    { value: 'junnar', label: 'Junnar', district: 'pune' },
    { value: 'ambegaon', label: 'Ambegaon', district: 'pune' },
    { value: 'mawal', label: 'Mawal', district: 'pune' },
    { value: 'mulshi', label: 'Mulshi', district: 'pune' },
    { value: 'shirur', label: 'Shirur', district: 'pune' },
    { value: 'purandar', label: 'Purandar', district: 'pune' },
    { value: 'velhe', label: 'Velhe', district: 'pune' },
    { value: 'bhor', label: 'Bhor', district: 'pune' },
    { value: 'baramati', label: 'Baramati', district: 'pune' },
    { value: 'indapur', label: 'Indapur', district: 'pune' },
    { value: 'daund', label: 'Daund', district: 'pune' },
    // Maharashtra -> Raigad
    { value: 'panvel', label: 'Panvel', district: 'raigad' },
    { value: 'pen', label: 'Pen', district: 'raigad' },
    { value: 'karjat-raigad', label: 'Karjat', district: 'raigad' },
    { value: 'khalapur', label: 'Khalapur', district: 'raigad' },
    { value: 'uran', label: 'Uran', district: 'raigad' },
    { value: 'alibaug', label: 'Alibaug', district: 'raigad' },
    { value: 'sudhagad', label: 'Sudhagad', district: 'raigad' },
    { value: 'mangaon', label: 'Mangaon', district: 'raigad' },
    { value: 'tala', label: 'Tala', district: 'raigad' },
    { value: 'roha', label: 'Roha', district: 'raigad' },
    { value: 'murud', label: 'Murud', district: 'raigad' },
    { value: 'mhasla', label: 'Mhasla', district: 'raigad' },
    { value: 'shrivardhan', label: 'Shrivardhan', district: 'raigad' },
    { value: 'mahad', label: 'Mahad', district: 'raigad' },
    { value: 'poladpur', label: 'Poladpur', district: 'raigad' },
    // Maharashtra -> Ratnagiri
    { value: 'ratnagiri', label: 'Ratnagiri', district: 'ratnagiri' },
    { value: 'sangameshwar', label: 'Sangameshwar', district: 'ratnagiri' },
    { value: 'lanja', label: 'Lanja', district: 'ratnagiri' },
    { value: 'rajapur', label: 'Rajapur', district: 'ratnagiri' },
    { value: 'chiplun', label: 'Chiplun', district: 'ratnagiri' },
    { value: 'guhagar', label: 'Guhagar', district: 'ratnagiri' },
    { value: 'dapoli', label: 'Dapoli', district: 'ratnagiri' },
    { value: 'mandangad', label: 'Mandangad', district: 'ratnagiri' },
    { value: 'khed-ratnagiri', label: 'Khed', district: 'ratnagiri' },
    // Maharashtra -> Sangli
    { value: 'miraj', label: 'Miraj', district: 'sangli' },
    { value: 'kavathe-mahankal', label: 'Kavathe-Mahankal', district: 'sangli' },
    { value: 'tasgaon', label: 'Tasgaon', district: 'sangli' },
    { value: 'jat', label: 'Jat', district: 'sangli' },
    { value: 'walwa', label: 'Walwa', district: 'sangli' },
    { value: 'shirala', label: 'Shirala', district: 'sangli' },
    { value: 'khanapur', label: 'Khanapur', district: 'sangli' },
    { value: 'atpadi', label: 'Atpadi', district: 'sangli' },
    { value: 'palus', label: 'Palus', district: 'sangli' },
    { value: 'kadegaon', label: 'Kadegaon', district: 'sangli' },
    // Maharashtra -> Satara
    { value: 'satara', label: 'Satara', district: 'satara' },
    { value: 'karad', label: 'Karad', district: 'satara' },
    { value: 'wai', label: 'Wai', district: 'satara' },
    { value: 'mahabaleshwar', label: 'Mahabaleshwar', district: 'satara' },
    { value: 'khandala', label: 'Khandala', district: 'satara' },
    { value: 'phaltan', label: 'Phaltan', district: 'satara' },
    { value: 'man', label: 'Man', district: 'satara' },
    { value: 'khatav', label: 'Khatav', district: 'satara' },
    { value: 'koregaon', label: 'Koregaon', district: 'satara' },
    { value: 'patan-satara', label: 'Patan', district: 'satara' },
    { value: 'jaoli', label: 'Jaoli', district: 'satara' },
    // Maharashtra -> Sindhudurg
    { value: 'kankavli', label: 'Kankavli', district: 'sindhudurg' },
    { value: 'vaibhavwadi', label: 'Vaibhavwadi', district: 'sindhudurg' },
    { value: 'devgad', label: 'Devgad', district: 'sindhudurg' },
    { value: 'malwan', label: 'Malwan', district: 'sindhudurg' },
    { value: 'sawantwadi', label: 'Sawantwadi', district: 'sindhudurg' },
    { value: 'kudal', label: 'Kudal', district: 'sindhudurg' },
    { value: 'vengurla', label: 'Vengurla', district: 'sindhudurg' },
    { value: 'doda-marg', label: 'Doda Marg', district: 'sindhudurg' },
    // Maharashtra -> Solapur
    { value: 'solapur-north', label: 'Solapur North', district: 'solapur' },
    { value: 'solapur-south', label: 'Solapur South', district: 'solapur' },
    { value: 'akkalkot', label: 'Akkalkot', district: 'solapur' },
    { value: 'barshi', label: 'Barshi', district: 'solapur' },
    { value: 'mangalwedha', label: 'Mangalwedha', district: 'solapur' },
    { value: 'pandharpur', label: 'Pandharpur', district: 'solapur' },
    { value: 'sangola', label: 'Sangola', district: 'solapur' },
    { value: 'malshiras', label: 'Malshiras', district: 'solapur' },
    { value: 'mohol', label: 'Mohol', district: 'solapur' },
    { value: 'karmala', label: 'Karmala', district: 'solapur' },
    { value: 'madha', label: 'Madha', district: 'solapur' },
    // Maharashtra -> Thane
    { value: 'thane', label: 'Thane', district: 'thane' },
    { value: 'kalyan', label: 'Kalyan', district: 'thane' },
    { value: 'murbad', label: 'Murbad', district: 'thane' },
    { value: 'bhiwandi', label: 'Bhiwandi', district: 'thane' },
    { value: 'shahapur', label: 'Shahapur', district: 'thane' },
    { value: 'ulhasnagar', label: 'Ulhasnagar', district: 'thane' },
    { value: 'ambarnath', label: 'Ambernath', district: 'thane' },
    // Maharashtra -> Wardha
    { value: 'wardha', label: 'Wardha', district: 'wardha' },
    { value: 'deoli', label: 'Deoli', district: 'wardha' },
    { value: 'seloo', label: 'Seloo', district: 'wardha' },
    { value: 'arvi', label: 'Arvi', district: 'wardha' },
    { value: 'asanji', label: 'Ashti', district: 'wardha' },
    { value: 'karanja', label: 'Karanja', district: 'wardha' },
    { value: 'hinganghat', label: 'Hinganghat', district: 'wardha' },
    { value: 'samudrapur', label: 'Samudrapur', district: 'wardha' },
    // Maharashtra -> Washim
    { value: 'washim', label: 'Washim', district: 'washim' },
    { value: 'malegaon-washim', label: 'Malegaon', district: 'washim' },
    { value: 'risod', label: 'Risod', district: 'washim' },
    { value: 'mangrulpir', label: 'Mangrulpir', district: 'washim' },
    { value: 'manora', label: 'Manora', district: 'washim' },
    { value: 'karanja-lad', label: 'Karanja Lad', district: 'washim' },
    // Maharashtra -> Yavatmal
    { value: 'yavatmal', label: 'Yavatmal', district: 'yavatmal' },
    { value: 'babhulgaon', label: 'Babhulgaon', district: 'yavatmal' },
    { value: 'kalamb-yavatmal', label: 'Kalamb', district: 'yavatmal' },
    { value: 'darwha', label: 'Darwha', district: 'yavatmal' },
    { value: 'digras', label: 'Digras', district: 'yavatmal' },
    { value: 'ner', label: 'Ner', district: 'yavatmal' },
    { value: 'pusad', label: 'Pusad', district: 'yavatmal' },
    { value: 'umarkhed', label: 'Umarkhed', district: 'yavatmal' },
    { value: 'mahagaon', label: 'Mahagaon', district: 'yavatmal' },
    { value: 'kelapur', label: 'Kelapur', district: 'yavatmal' },
    { value: 'ralegaon', label: 'Ralegaon', district: 'yavatmal' },
    { value: 'ghatanji', label: 'Ghatanji', district: 'yavatmal' },
    { value: 'pandharkawada', label: 'Pandharkawada', district: 'yavatmal' },
    { value: 'wani', label: 'Wani', district: 'yavatmal' },
    { value: 'maregaon', label: 'Maregaon', district: 'yavatmal' },
    { value: 'zari-jamani', label: 'Zari Jamani', district: 'yavatmal' },

    // Gujarat -> Ahmedabad
    { value: 'ahmedabad-city-taluka', label: 'Ahmedabad City', district: 'ahmedabad' },
    { value: 'daskroi', label: 'Daskroi', district: 'ahmedabad' },
    { value: 'dholka', label: 'Dholka', district: 'ahmedabad' },
    { value: 'bavla', label: 'Bavla', district: 'ahmedabad' },
    { value: 'sanand', label: 'Sanand', district: 'ahmedabad' },
    { value: 'viramgam', label: 'Viramgam', district: 'ahmedabad' },
    { value: 'mandal', label: 'Mandal', district: 'ahmedabad' },
    { value: 'detroj-rampura', label: 'Detroj-Rampura', district: 'ahmedabad' },
    { value: 'dhandhuka', label: 'Dhandhuka', district: 'ahmedabad' },
    { value: 'dholera', label: 'Dholera', district: 'ahmedabad' },
];

export const cities = [
    // Maharashtra -> Pune
    { value: 'pune', label: 'Pune', taluka: 'pune-city' },
    { value: 'pimpri-chinchwad', label: 'Pimpri-Chinchwad', taluka: 'pune-city' },
    { value: 'baramati-city', label: 'Baramati', taluka: 'baramati' },
    { value: 'lonavla', label: 'Lonavla', taluka: 'mawal' },
    
    // Maharashtra -> Nagpur
    { value: 'nagpur-city', label: 'Nagpur', taluka: 'nagpur-urban' },
    
    // Gujarat -> Ahmedabad
    { value: 'ahmedabad-city', label: 'Ahmedabad', taluka: 'ahmedabad-city-taluka' },
    
    // Gujarat -> Gandhinagar
    { value: 'gandhinagar-city', label: 'Gandhinagar', district: 'gandhinagar' },

    // Cities for Akola District
    { value: 'akola-city', label: 'Akola', taluka: 'akola' },
    { value: 'akot-city', label: 'Akot', taluka: 'akot' },
    { value: 'murtijapur-city', label: 'Murtijapur', taluka: 'murtijapur' },
    { value: 'telhara-city', label: 'Telhara', taluka: 'telhara' },
    { value: 'balapur-city', label: 'Balapur', taluka: 'balapur' },
    { value: 'patoor-city', label: 'Patoor', taluka: 'patoor' },
    { value: 'barshitakli-city', label: 'Barshitakli', taluka: 'barshitakli' },

    // Cities for Amravati District
    { value: 'amravati-city', label: 'Amravati', taluka: 'amravati' },
    { value: 'achalpur-city', label: 'Achalpur', taluka: 'achlapur' },
    { value: 'warud-city', label: 'Warud', taluka: 'warud' },
    { value: 'daryapur-city', label: 'Daryapur', taluka: 'daryapur' },
    { value: 'morshi-city', label: 'Morshi', taluka: 'morshi' },

    // Cities for Buldhana District
    { value: 'buldhana-city', label: 'Buldhana', taluka: 'buldhana' },
    { value: 'khamgaon-city', label: 'Khamgaon', taluka: 'khamgaon' },
    { value: 'malkapur-city', label: 'Malkapur', taluka: 'malkapur' },
    { value: 'shegaon-city', label: 'Shegaon', taluka: 'shegaon' },
    { value: 'chikhli-city', label: 'Chikhli', taluka: 'chikhli' },

    // Cities for Yavatmal District
    { value: 'yavatmal-city', label: 'Yavatmal', taluka: 'yavatmal' },
    { value: 'pusad-city', label: 'Pusad', taluka: 'pusad' },
    { value: 'wani-city', label: 'Wani', taluka: 'wani' },
    { value: 'umarkhed-city', label: 'Umarkhed', taluka: 'umarkhed' },

    // Cities for Washim District
    { value: 'washim-city', label: 'Washim', taluka: 'washim' },
    { value: 'karanja-lad-city', label: 'Karanja Lad', taluka: 'karanja-lad' },
    { value: 'risod-city', label: 'Risod', taluka: 'risod' },
    { value: 'mangrulpir-city', label: 'Mangrulpir', taluka: 'mangrulpir' },
    
    // Ahmednagar
    { value: 'ahmednagar-city', label: 'Ahmednagar', taluka: 'nagar'},
    { value: 'sangamner-city', label: 'Sangamner', taluka: 'sangamner'},
    { value: 'kopargaon-city', label: 'Kopargaon', taluka: 'kopargaon'},
    { value: 'shrirampur-city', label: 'Shrirampur', taluka: 'shrirampur'},
    { value: 'rahuri-city', label: 'Rahuri', taluka: 'rahuri'},

    // Aurangabad
    { value: 'aurangabad-city', label: 'Aurangabad', taluka: 'aurangabad'},
    { value: 'vaijapur-city', label: 'Vaijapur', taluka: 'vaijapur'},
    { value: 'gangapur-city', label: 'Gangapur', taluka: 'gangapur'},
    { value: 'paithan-city', label: 'Paithan', taluka: 'paithan'},
    { value: 'sillod-city', label: 'Sillod', taluka: 'sillod'},

    // Beed
    { value: 'beed-city', label: 'Beed', taluka: 'beed'},
    { value: 'ambajogai-city', label: 'Ambajogai', taluka: 'ambajogai'},
    { value: 'parli-city', label: 'Parli', taluka: 'parli'},

    // Bhandara
    { value: 'bhandara-city', label: 'Bhandara', taluka: 'bhandara'},
    { value: 'tumsar-city', label: 'Tumsar', taluka: 'tumsar'},

    // Chandrapur
    { value: 'chandrapur-city', label: 'Chandrapur', taluka: 'chandrapur'},
    { value: 'ballarpur-city', label: 'Ballarpur', taluka: 'ballarpur'},
    { value: 'warora-city', label: 'Warora', taluka: 'warora'},

    // Dhule
    { value: 'dhule-city', label: 'Dhule', taluka: 'dhule'},
    { value: 'shirpur-city', label: 'Shirpur', taluka: 'shirpur'},

    // Gadchiroli
    { value: 'gadchiroli-city', label: 'Gadchiroli', taluka: 'gadchiroli'},

    // Gondia
    { value: 'gondia-city', label: 'Gondia', taluka: 'gondia'},
    { value: 'tiroda-city', label: 'Tiroda', taluka: 'tiroda'},

    // Hingoli
    { value: 'hingoli-city', label: 'Hingoli', taluka: 'hingoli'},
    { value: 'basmath-city', label: 'Basmath', taluka: 'basmath'},

    // Jalgaon
    { value: 'jalgaon-city', label: 'Jalgaon', taluka: 'jalgaon'},
    { value: 'bhusawal-city', label: 'Bhusawal', taluka: 'bhusawal'},
    { value: 'chalisgaon-city', label: 'Chalisgaon', taluka: 'chalisgaon'},
    { value: 'amalner-city', label: 'Amalner', taluka: 'amalner'},
    { value: 'chopda-city', label: 'Chopda', taluka: 'chopda'},

    // Jalna
    { value: 'jalna-city', label: 'Jalna', taluka: 'jalna'},
    { value: 'ambad-city', label: 'Ambad', taluka: 'ambad'},
    { value: 'partur-city', label: 'Partur', taluka: 'partur'},

    // Kolhapur
    { value: 'kolhapur-city', label: 'Kolhapur', taluka: 'karvir'},
    { value: 'ichalkaranji-city', label: 'Ichalkaranji', taluka: 'hatkanangle'},

    // Latur
    { value: 'latur-city', label: 'Latur', taluka: 'latur'},
    { value: 'udgir-city', label: 'Udgir', taluka: 'udgir'},
    { value: 'ahmedpur-city', label: 'Ahmedpur', taluka: 'ahmedpur'},

    // Mumbai
    { value: 'mumbai', label: 'Mumbai', taluka: 'kurla'},
    { value: 'mumbai-andheri', label: 'Mumbai', taluka: 'andheri'},
    { value: 'mumbai-borivali', label: 'Mumbai', taluka: 'borivali'},

    // Nanded
    { value: 'nanded-city', label: 'Nanded', taluka: 'nanded'},
    { value: 'deglur-city', label: 'Deglur', taluka: 'deglur'},
    { value: 'dharmabad-city', label: 'Dharmabad', taluka: 'dharmabad'},

    // Nandurbar
    { value: 'nandurbar-city', label: 'Nandurbar', taluka: 'nandurbar'},
    { value: 'shahada-city', label: 'Shahada', taluka: 'shahada'},

    // Nashik
    { value: 'nashik-city', label: 'Nashik', taluka: 'nashik'},
    { value: 'malegaon-city', label: 'Malegaon', taluka: 'malegaon'},
    { value: 'manmad-city', label: 'Manmad', taluka: 'nandgaon'},
    { value: 'sinnar-city', label: 'Sinnar', taluka: 'sinnar'},

    // Osmanabad
    { value: 'osmanabad-city', label: 'Osmanabad', taluka: 'osmanabad'},
    { value: 'umaraga-city', label: 'Umaraga', taluka: 'umaraga'},

    // Palghar
    { value: 'vasai-virar-city', label: 'Vasai-Virar', taluka: 'vasai'},
    { value: 'palghar-city', label: 'Palghar', taluka: 'palghar'},
    { value: 'dahanu-city', label: 'Dahanu', taluka: 'dahanu'},

    // Parbhani
    { value: 'parbhani-city', label: 'Parbhani', taluka: 'parbhani'},
    { value: 'sailu-city', label: 'Sailu', taluka: 'sailu'},
    { value: 'gangakhed-city', label: 'Gangakhed', taluka: 'gangakhed'},

    // Raigad
    { value: 'panvel-city', label: 'Panvel', taluka: 'panvel'},
    { value: 'alibaug-city', label: 'Alibaug', taluka: 'alibaug'},
    { value: 'pen-city', label: 'Pen', taluka: 'pen'},
    { value: 'mahad-city', label: 'Mahad', taluka: 'mahad'},

    // Ratnagiri
    { value: 'ratnagiri-city', label: 'Ratnagiri', taluka: 'ratnagiri'},
    { value: 'chiplun-city', label: 'Chiplun', taluka: 'chiplun'},
    { value: 'khed-city-ratnagiri', label: 'Khed', taluka: 'khed-ratnagiri'},

    // Sangli
    { value: 'sangli-miraj-kupwad', label: 'Sangli-Miraj-Kupwad', taluka: 'miraj'},
    { value: 'islampur-city', label: 'Islampur', taluka: 'walwa'},

    // Satara
    { value: 'satara-city', label: 'Satara', taluka: 'satara'},
    { value: 'karad-city', label: 'Karad', taluka: 'karad'},
    { value: 'phalton-city', label: 'Phaltan', taluka: 'phaltan'},

    // Sindhudurg
    { value: 'sawantwadi-city', label: 'Sawantwadi', taluka: 'sawantwadi'},
    { value: 'kankavli-city', label: 'Kankavli', taluka: 'kankavli'},
    { value: 'malwan-city', label: 'Malwan', taluka: 'malwan'},

    // Solapur
    { value: 'solapur-city', label: 'Solapur', taluka: 'solapur-north'},
    { value: 'pandharpur-city', label: 'Pandharpur', taluka: 'pandharpur'},
    { value: 'barshi-city', label: 'Barshi', taluka: 'barshi'},
    { value: 'akkalkot-city', label: 'Akkalkot', taluka: 'akkalkot'},

    // Thane
    { value: 'thane-city', label: 'Thane', taluka: 'thane'},
    { value: 'kalyan-dombivli-city', label: 'Kalyan-Dombivli', taluka: 'kalyan'},
    { value: 'ulhasnagar-city', label: 'Ulhasnagar', taluka: 'ulhasnagar'},
    { value: 'bhiwandi-nizampur-city', label: 'Bhiwandi-Nizampur', taluka: 'bhiwandi'},
    { value: 'mira-bhayandar-city', label: 'Mira-Bhayandar', taluka: 'thane'}, // Often considered part of Thane
    { value: 'navi-mumbai-city', label: 'Navi Mumbai', taluka: 'thane'}, // Often considered part of Thane

    // Wardha
    { value: 'wardha-city', label: 'Wardha', taluka: 'wardha'},
    { value: 'hinganghat-city', label: 'Hinganghat', taluka: 'hinganghat'},
    { value: 'arvi-city', label: 'Arvi', taluka: 'arvi'},
];


export const languages = [
    { value: 'marathi', label: 'Marathi' },
    { value: 'hindi', label: 'Hindi' },
    { value: 'english', label: 'English' },
    { value: 'gujarati', label: 'Gujarati' },
    { value: 'kannada', label: 'Kannada' },
    { value: 'telugu', label: 'Telugu' },
    { value: 'tamil', label: 'Tamil' },
];

