
// This file is not to be modified.
// It is automatically generated by the Firebase setup.
// For more details, see the Firebase Usage Instructions.

'use client';

import { ReactNode, useMemo } from 'react';
import { FirebaseProvider } from './provider';
import { initializeFirebase } from './index';
import { FirebaseErrorListener } from '@/components/FirebaseErrorListener';

export function FirebaseClientProvider({ children }: { children: ReactNode }) {
  const firebaseServices = useMemo(() => initializeFirebase(), []);

  return (
    <FirebaseProvider
      value={{
        firebaseApp: firebaseServices.firebaseApp,
        auth: firebaseServices.auth,
        firestore: firebaseServices.firestore,
        database: firebaseServices.database,
        storage: firebaseServices.storage,
      }}
    >
      <FirebaseErrorListener />
      {children}
    </FirebaseProvider>
  );
}
