
// This file is not to be modified.
// It is automatically generated by the Firebase setup.
// For more details, see the Firebase Usage Instructions.

import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
 apiKey: "AIzaSyDVFBCYVHlFe5diH2gbeVrg54IShEzXFzg",
  authDomain: "national-skill-sector.firebaseapp.com",
  databaseURL: "https://national-skill-sector-default-rtdb.firebaseio.com",
  projectId: "national-skill-sector",
  storageBucket: "national-skill-sector.firebasestorage.app",
  messagingSenderId: "332795147843",
  appId: "1:332795147843:web:8c973fbbb8c7cad30d06f6",
  measurementId: "G-8RFB9CQMQM"
};
