
// This file is not to be modified.
// It is automatically generated by the Firebase setup.
// For more details, see the Firebase Usage Instructions.
import { EventEmitter } from 'events';

// Since we're in a browser environment, we might need a polyfill for 'events'
// but Next.js/Webpack usually handles this.
// If not, a library like `eventemitter3` can be used.

// Export a singleton instance of the event emitter
export const errorEmitter = new EventEmitter();
